# Generated by Django 6.0.3 on 2026-03-06 00:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicDatabase",
            fields=[
                (
                    "topic_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "topic_name",
                    models.CharField(
                        choices=[
                            ("ব্যবসা (Business)", "ব্যবসা (Business)"),
                            (
                                "ব্যক্তিগত অর্থায়ন (Personal Finance)",
                                "ব্যক্তিগত অর্থায়ন (Personal Finance)",
                            ),
                            (
                                "কাস্টমার সাপোর্ট (Customer Support)",
                                "কাস্টমার সাপোর্ট (Customer Support)",
                            ),
                            ("রাজনীতি (Politics)", "রাজনীতি (Politics)"),
                            (
                                "ব্যাংকিং প্রশ্নাবলী (Banking)",
                                "ব্যাংকিং প্রশ্নাবলী (Banking)",
                            ),
                            ("কল সেন্টার (Call Center)", "কল সেন্টার (Call Center)"),
                            ("খেলাধুলা (Sports)", "খেলাধুলা (Sports)"),
                            (
                                "সংবাদপত্রে আসার মতো গুরুত্বপূর্ণ বিষয় (Newspaper-worthy topics)",
                                "সংবাদপত্রে আসার মতো গুরুত্বপূর্ণ বিষয় (Newspaper-worthy topics)",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("script", models.TextField()),
                ("is_done", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("whatsapp_number", models.CharField(max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("district", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingDatabase",
            fields=[
                (
                    "meeting_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("host_mail_id", models.EmailField(max_length=254)),
                (
                    "guest_mail_id",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("meeting_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "waiting"),
                            ("paired", "paired"),
                            ("completed", "completed"),
                            ("expired", "expired"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "studio_host_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "studio_guest_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("host_name", models.CharField(blank=True, max_length=255, null=True)),
                ("guest_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "played_topics",
                    models.ManyToManyField(
                        blank=True,
                        related_name="played_in_meetings",
                        to="core.topicdatabase",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.topicdatabase",
                    ),
                ),
            ],
        ),
    ]
