# Generated by Django 6.0.3 on 2026-03-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudioLinkDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_id", models.CharField(max_length=255)),
                ("email1", models.EmailField(max_length=254)),
                ("email2", models.EmailField(max_length=254)),
                ("meeting_url", models.URLField(max_length=500)),
                ("is_used", models.BooleanField(default=False)),
            ],
        ),
    ]
