# Generated by Django 6.0.3 on 2026-03-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_studiolinkdatabase"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingdatabase",
            name="last_script_change_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meetingdatabase",
            name="played_topic_ids_comma_separated",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="meetingdatabase",
            name="valid_script_count",
            field=models.IntegerField(default=0),
        ),
    ]
