# Generated by Django 5.1.3 on 2026-03-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_meetingdatabase_data_taken_meetingdatabase_guest_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
