# Generated by Django 5.1.3 on 2026-03-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_user_contact_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingdatabase",
            name="joined_meeting_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="meetingdatabase",
            name="status",
            field=models.CharField(
                choices=[
                    ("searching", "searching"),
                    ("joined_other", "joined_other"),
                    ("waiting", "waiting"),
                    ("paired", "paired"),
                    ("completed", "completed"),
                    ("expired", "expired"),
                    ("timeout", "timeout"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
