# Generated by Django 5.1.3 on 2026-03-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_meetingdatabase_joined_meeting_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingdatabase",
            name="guest_done_script",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meetingdatabase",
            name="host_done_script",
            field=models.BooleanField(default=False),
        ),
    ]
