# Generated by Django 5.1.3 on 2026-03-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_meetingdatabase_guest_done_script_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingdatabase",
            name="guest_last_heartbeat",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meetingdatabase",
            name="host_last_heartbeat",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
