# Generated by Django 5.1.3 on 2026-03-10 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_meetingdatabase_guest_last_heartbeat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studiolinkdatabase",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.topicdatabase",
            ),
        ),
    ]
