# Generated by Django 5.1.3 on 2026-03-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_studiolinkdatabase_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studiolinkdatabase",
            name="topic",
        ),
        migrations.AddField(
            model_name="studiolinkdatabase",
            name="topic_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ব্যবসা (Business)", "ব্যবসা (Business)"),
                    (
                        "ব্যক্তিগত অর্থায়ন (Personal Finance)",
                        "ব্যক্তিগত অর্থায়ন (Personal Finance)",
                    ),
                    (
                        "কাস্টমার সাপোর্ট (Customer Support)",
                        "কাস্টমার সাপোর্ট (Customer Support)",
                    ),
                    ("রাজনীতি (Politics)", "রাজনীতি (Politics)"),
                    ("ব্যাংকিং প্রশ্নাবলী (Banking)", "ব্যাংকিং প্রশ্নাবলী (Banking)"),
                    ("কল সেন্টার (Call Center)", "কল সেন্টার (Call Center)"),
                    ("খেলাধুলা (Sports)", "খেলাধুলা (Sports)"),
                    (
                        "সংবাদপত্রে আসার মতো গুরুত্বপূর্ণ বিষয় (Newspaper-worthy topics)",
                        "সংবাদপত্রে আসার মতো গুরুত্বপূর্ণ বিষয় (Newspaper-worthy topics)",
                    ),
                ],
                help_text="Select the topic category for this studio link",
                max_length=255,
                null=True,
            ),
        ),
    ]
