# Generated by Django 5.1.3 on 2026-03-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_studiolinkdatabase_topic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studiolinkdatabase",
            name="last_used_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
